version: '3'
services:
  redis: 
    image: 'redis'
    ports:
        - "6379:6379"
  node:
    image: 'baris/app'
    depends_on:
        - redis
    build: .
    ports:
      - "3000:3000"
    environment:
        REDIS_HOST: redis