# This is a basic workflow to help you get started with Actions

name: pushtoecr

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Push to Amazon ECR
        uses: jwalton/gh-ecr-push@v1.0.0
        
      - run: docker build --tag ${{ secrets.AWS_SECRET_CONTAINERNAME }} .
      - name: Push to ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_SECRET_REGION }}
          image: ${{ secrets.AWS_SECRET_CONTAINERNAME }}
